name: Test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./datadragon

      - name: Test
        run: go test -v ./datadragon

      - name: Integration tests
        if: github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'develop'
        run: go test -tags integration -v ./datadragon